require('balanced-dashboard/models/core/adapters/base');
require('balanced-dashboard/models/core/adapters/ajax');
require('balanced-dashboard/models/core/adapters/base');
require('balanced-dashboard/models/core/adapters/fixture');
require('balanced-dashboard/models/core/adapter_config');
require('balanced-dashboard/models/core/model');
require('balanced-dashboard/models/core/serializers/base');
require('balanced-dashboard/models/core/serializers/rev0');
require('balanced-dashboard/models/core/serializers/rev1');
